config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks
  end

  root "lists#index"
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  has_and_belongs_to_many :tags

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    if params[:archived].present?
      @lists = List.where(archived: true)
    else
      @lists = List.where(archived: false)
    end
  end

  def show
    @list = List.find(params[:id])
    @task = Task.new

    if params[:completed].present?
      @tasks = @list.tasks.where(status: "complete")
    else
      @tasks = @list.tasks.where(status: "incomplete")
    end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      flash[:notice] = "List successfully created"
      redirect_to lists_path
    else
      flash[:error] = "Unable to create list"
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(list_params)
      respond_to do |format|
        format.html do
          flash[:notice] = "List successfully updated"
          redirect_to lists_path
        end
        format.json do
          render json: @list
        end
      end
    else
      flash[:error] = "Unable to update list"
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :archived)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :find_list

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      flash[:notice] = "Task successfully saved"
      redirect_to list_path(id: @list.id)
    else
      flash[:error] = "Unable to save task"
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      respond_to do |format|
        format.html do
          flash[:notice] = "Task successfully updated"
          redirect_to list_path(id: @list.id)
        end
        format.json do
          render json: @task
        end
      end
    else
      flash[:error] = "Unable to update task"
      render :new
    end
  end

  private

  def task_params
    params.require(:task).permit(:title,
                                 :description,
                                 :status,
                                 :due_date,
                                 :list_id,
                                 :tag_ids => [])
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManagerii</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css" />
  <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "flash-#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render "form" %>

app/views/lists/index.html.erb
<h1>All Lists</h1>

<table>
  <tr>
    <th>Title</th>
    <% if params[:archived].present? %>
    <th>Unarchive</th>
    <% else %>
    <th>Archive</th>
    <% end %>
  </tr>
  <% @lists.each do |list| %>
  <tr id="list-row-<%= list.id %>">
    <td id="list-title"><%= link_to list.title, list_path(id: list.id) %></td>
    <td id="archive-status">
      <% if list.archived == false %>
        <input type="checkbox" class="list-checkbox" id="<%= list.id%>" value="Completed"
        onClick="markListArchived(<%= list.id %>);">
      <% else %>
        <input type="checkbox" class="list-checkbox" id="<%= list.id%>" value="Not-Completed"
        onClick="markListUnarchived(<%= list.id %>);">
      <% end %>
    </td>
  </tr>
  <% end %>
</table>



<p><%= link_to "Unarchived Lists", lists_path %></p>
<p><%= link_to "Archived Lists", lists_path(archived: true) %></p>


<p><%= link_to "Create new list", new_list_path %></p>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form" %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>

<h3>Tasks</h3>
<table id="tasks-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Due Date</th>
      <th>Tags</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr id="task-row-<%= task.id %>">
        <td><%= link_to task.title, list_task_path(list_id: @list.id, id: task.id) %></td>
        <td><%= task.description %></td>
        <td><%= task.status %>
          <% if task.status == "incomplete" %>
            <input type="checkbox" class="task-checkbox" id="<%= task.id%>" value="Completed"
            onClick="markTaskComplete(<%= @list.id %>, <%= task.id %>);">
          <% else %>
            <input type="checkbox" class="task-checkbox" id="<%= task.id%>" value="Not-Completed"
            onClick="markTaskIncomplete(<%= @list.id %>, <%= task.id %>);">
          <% end %>
        </td>
        <td><%= task.due_date %></td>
        <% task.tags.each do |tag| %>
        <td><%= tag.name %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>New Task</h3>
<%= form_for([@list, @task]) do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :due_date %>
  <%= date_select(:task, :due_date) %>

  <%= f.label :tags %>
  <%= f.collection_select :tag_ids, Tag.all, :id, :name, {},
  {:multiple => true} %>

  <%= f.hidden_field(:list_id, value: @list.id) %>

  <%= f.submit "Submit" %>
</div>
<% end %>

<p><%= link_to "Uncompleted Tasks", list_path(id: @list.id) %></p>
<p><%= link_to "Completed Tasks", list_path(id: @list.id, completed: true) %></p>

<div>
  <p><%= link_to "Edit list", edit_list_path(id: @list.id) %></p>
  <p><%= link_to "Delete list", list_path(id: @list.id), method: :delete %></p>
  <p><%= link_to "All lists", lists_path %></p>
</div><br />

app/views/tasks/_form.html.erb
<%= form_for([@list, @task]) do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :due_date %>
  <%= date_select(:task, :due_date) %>

  <%= f.hidden_field(:list_id, value: @list.id) %>

  <%= f.submit "Submit" %>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render "form" %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h3>Description:  <%= @task.description %></h3>
<h3>Status:  <%= @task.status %></h3>
<h3>Tags: 
  <% @task.tags.each do |tag| %>
    <%= tag.name %>
  <% end %>
</h3>

<p><%= link_to "Edit Task", edit_list_task_path(list_id: @task.list_id, id: @task.id) %></p>
<p><%= link_to "All tasks", list_path(id: @task.list_id) %></p>